name: "[Legacy] Check if the Flutter submodule is up to date"
on:
  workflow_dispatch:

jobs:
  check-flutter-submodule:
    name: Check if the Flutter submodule is up to date
    runs-on: ubuntu-slim
    if: ${{ github.repository == 'saber-notes/saber' }}
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Check if the Flutter submodule is up to date
        run: dart .github/scripts/check_flutter_submodule.dart

