name: "[Legacy] Top issues"
on:
  workflow_dispatch:

jobs:
  top-issues:
    name: Top issues
    runs-on: ubuntu-slim
    if: ${{ github.repository == 'saber-notes/saber' }}
    timeout-minutes: 5
    steps:
      - name: Run top issues action
        uses: rickstaa/top-issues-action@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          top_bugs: true
          top_features: true
          top_pull_requests: true

